meta_title: "Barber.App"
meta_description: "Find a Barber near you"
meta_image: "winners-ribbon.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@RoeldJ92" # indispensable pour les Twitter Cards
