meta_title "Barber.App"
meta_description "Find a Barber near you"
meta_image "meta-page.jpg" # A picture in your app / assets / images /
twitter_account "@nomdevotrecompte" # essential for Twitter Cards
