# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6353d9946d2fc9a596cc47097cfeb64b5eb4500de30a8d043095b14adfe0e498a971e395ab882097b43a47fb36a61531f4dbbbf122f4563ae0213e7d22ccec2b

test:
  secret_key_base: 65bb20e25e86b1188a30aab75b841f51ec57ab5005db74a6547714b3410c092a5509e6e265d92c9c39e5970d441beb7e4226e75667afb1210a144bf72fc1a516

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
